UPDATE DELIVERABLE_PROJECT SET Project_Title = "Medical Chatbot" WHERE Project_ID = 1005;

UPDATE GUIDE SET USN = '1RV20IS045' WHERE GUIDE_ID = '1201';
UPDATE GUIDE SET USN = '1RV20IS043' WHERE GUIDE_ID = '1204';
UPDATE GUIDE SET USN = '1RV20IS036' WHERE GUIDE_ID = '1203';
UPDATE GUIDE SET USN = '1RV20IS006' WHERE GUIDE_ID = '1202';

CREATE TABLE PANEL_ALLOT (
ALLOT_NUM INTEGER PRIMARY KEY AUTO_INCREMENT,
GUIDE_ID VARCHAR(25),
PANEL_ID INTEGER,
FOREIGN KEY (GUIDE_ID) REFERENCES GUIDE(GUIDE_ID),
FOREIGN KEY (PANEL_ID) REFERENCES PANEL_MEMBERS(PANEL_ID)
);

INSERT INTO PANEL_ALLOT (Guide_ID,Panel_ID) VALUES ('1201',100), ('1202',104), ('1203',102), ('1204',103);

CREATE TABLE PHASE_ALLOT (
phase_ID INTEGER PRIMARY KEY auto_increment,
Project_ID INTEGER,
phase_no INTEGER,
due_date DATE,
FOREIGN KEY (Project_ID) REFERENCES DELIVERABLE_PROJECT(Project_ID)
);

INSERT INTO PHASE_ALLOT VALUES (1203,1003,1,20222-09-03);
INSERT INTO PHASE_ALLOT VALUES (1204,1004,1,20222-10-04);
INSERT INTO PHASE_ALLOT VALUES (1205,1005,0,20222-10-23);
INSERT INTO PHASE_ALLOT VALUES (1206,1006,0,20222-09-03);

SELECT * FROM PHASE_ALLOT;

UPDATE PHASE_ALLOT SET Phase_ID = 1303 WHERE Phase_ID = 1203;
UPDATE PHASE_ALLOT SET Phase_ID = 1304 WHERE Phase_ID = 1204;

UPDATE PHASE_ALLOT SET LATE_SUBMISSION = "LATE" WHERE PHASE_ID = 1301;
UPDATE PHASE_ALLOT SET LATE_SUBMISSION = "LATE" WHERE PHASE_ID = 1302;

#Update as of 01-02-2023
nSELECT D.PROJECT_TITLE,D.PROJECT_DOMAIN,G.FIRST_NAME,G.LAST_NAME FROM DELIVERABLE_PROJECT AS D,STUDENT AS S,USERS AS U,PANEL_ALLOT AS P,GUIDE AS G WHERE D.USN = S.USN AND S.EMAIL = U.EMAIL AND D.PANEL_ID = P.PANEL_ID AND G.GUIDE_ID = P.GUIDE_ID;

SELECT FIRST_NAME AS GUIDE_FIRST_NAME,LAST_NAME AS GUIDE_LAST_NAME FROM GUIDE AS G,USERS AS U WHERE G.EMAIL = U.EMAIL;

ALTER TABLE GUIDE RENAME COLUMN ID TO DIARY_ID;

ALTER TABLE COORDINATOR DROP FOREIGN KEY coordinator_ibfk_4;
ALTER TABLE COORDINATOR DROP PANEL_ID;
ALTER TABLE COORDINATOR DROP FOREIGN KEY coordinator_ibfk_2;
ALTER TABLE COORDINATOR DROP ID;
ALTER TABLE COORDINATOR DROP FOREIGN KEY coordinator_ibfk_3;
ALTER TABLE COORDINATOR DROP USN;