INSERT INTO TRANSACTIONS VALUES  (11004,10042,'2023-03-21','ONTIME');
ALTER TABLE EVALUATE_RESULT 
ADD GUIDE_NO VARCHAR(25);
UPDATE EVALUATE_RESULT SET GUIDE_NO = '1201' WHERE USN = '1RV20IS045';
INSERT INTO PHASE_ALLOT VALUES ('10061','1006','1');
DELETE FROM FILE_SUB WHERE SUB_ID = '10061';
DELETE FROM FILE_SUB WHERE SUB_ID = '10061';
INSERT INTO EVALUATE_RESULT VALUES(10042,'1RV20IS045',10,4,4,'');
INSERT INTO EVALUATE_RESULT VALUES (10042,'1RV20IS045',10,4,4,'1201');
DELETE FROM EVALUATE_RESULT WHERE SUB_ID = '10061';
USE DEPT_PROJECT;

ALTER TABLE EVALUATE_RESULT ADD COLUMN RESULT INTEGER; 

-- SELECT F.SUB_ID,F.USN,ST.FIRST_NAME,ST.LAST_NAME,F.PHASE_NO,SC.PHASE_DESC,T.SUB_STATUS FROM FILE_SUB AS F,STUDENT AS ST,TRANSACTIONS AS T,SCHEDULE AS SC,GUIDE AS G WHERE F.USN = ST.USN AND F.PHASE_NO = SC.PHASE_NO AND T.SUB_ID = F.SUB_ID AND G.USN = ST.USN AND ST.EMAIL = 'shankartejasvi.is20@rvce.edu.in';
-- SELECT F.SUB_ID,F.PHASE_NO,SC.PHASE_DESC,T.SUB_STATUS,E.RESULT FROM FILE_SUB AS F,SCHEDULE AS SC,TRANSACTIONS AS T,EVALUATE_RESULT AS E,STUDENT AS ST WHERE F.USN = ST.USN AND F.PHASE_NO = SC.PHASE_NO AND T.SUB_ID = F.SUB_ID AND E.SUB_ID = F.SUB_ID AND ST.EMAIL = 'shankartejasvi.is20@rvce.edu.in'; 
-- SELECT
--   RUBRIC_1_MARKS + RUBRIC_2_MARKS + RUBRIC_3_MARKS AS "Total"
-- FROM EVALUATE_RESULT;
UPDATE EVALUATE_RESULT 
SET RESULT = RUBRIC_1_MARKS + RUBRIC_2_MARKS + RUBRIC_3_MARKS
WHERE SUB_ID = '10031' OR SUB_ID = '10042' OR SUB_ID = '10061';

ALTER TABLE FILE_SUB ADD COLUMN EVAL BOOLEAN;

UPDATE FILE_SUB
SET EVAL = TRUE 
WHERE SUB_ID = '10042' OR SUB_ID = '10061';
UPDATE FILE_SUB
SET EVAL = FALSE 
WHERE NOT SUB_ID = '10042' AND NOT SUB_ID = '10061';

-- SELECT F.SUB_ID,S.PHASE_NO,S.PHASE_DESC,T.SUBMITTED_AT FROM SCHEDULE AS S,TRANSACTIONS AS T,FILE_SUB AS F,PHASE_ALLOT AS PA, DELIVERABLE_PROJECT AS D WHERE S.PHASE_NO = F.PHASE_NO AND T.SUB_ID = PA.PHASE_ID AND F.USN = D.USN AND T.SUB_ID = F.SUB_ID AND F.EVAL = FALSE;
