ALTER TABLE STUDENT_SUB DROP FOREIGN KEY student_sub_ibfk_2;
ALTER TABLE STUDENT_SUB
DROP COLUMN PHASE_ID;

ALTER TABLE STUDENT_SUB
ADD PHASE_NO INTEGER;

ALTER TABLE STUDENT_SUB DROP COLUMN SUBMISSION_STATUS;

ALTER TABLE STUDENT_SUB
MODIFY FILE_SUBMIT BLOB;

UPDATE PHASE_ALLOT SET DUE_DATE = '2023-02-10' WHERE PHASE_ID = 1303;
UPDATE PHASE_ALLOT SET DUE_DATE = '2023-02-15' WHERE PHASE_ID = 1304;

CREATE TABLE STUDENT_SUB (
SUBMISSION_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
USN VARCHAR(25),
PHASE_ID INTEGER,
PROJECT_ID INTEGER,
SUBMITTED_AT DATETIME,
SUBMISSION_STATUS VARCHAR(25),
FOREIGN KEY (USN) REFERENCES STUDENT(USN) ON DELETE CASCADE,
FOREIGN KEY (PHASE_ID) REFERENCES PHASE_ALLOT(PHASE_ID) ON DELETE CASCADE,
FOREIGN KEY (PROJECT_ID) REFERENCES DELIVERABLE_PROJECT(PROJECT_ID)
);

CREATE TABLE SCHEDULE (
PHASE_NO INTEGER PRIMARY KEY,
PHASE_DESC INTEGER,
DUE_DATE DATE
);

SHOW TABLES;

ALTER TABLE SCHEDULE
MODIFY PHASE_DESC VARCHAR(100);

ALTER TABLE STUDENT_SUB
ADD FILE_SUBMIT VARCHAR(100);


INSERT INTO SCHEDULE (PHASE_NO,PHASE_DESC,DUE_DATE) VALUES
(1,'SYNOPSIS','2023-02-08'),
(2,'SRS','2023-02-13');


CREATE TABLE FILE_SUB (
SUB_ID INTEGER auto_increment PRIMARY KEY,
USN VARCHAR(25),
PHASE_NO INTEGER,
FILE VARCHAR(100) NOT NULL
);

ALTER TABLE PHASE_ALLOT
ADD FOREIGN KEY (PHASE_NO) REFERENCES SCHEDULE(PHASE_NO);

INSERT INTO PHASE_ALLOT VALUES (10032,1003,2,'2023-02-15');

UPDATE PHASE_ALLOT SET PHASE_ID = 10031 WHERE PHASE_ID = 1303;
UPDATE PHASE_ALLOT SET PHASE_ID = 10042 WHERE PHASE_ID = 1304;

UPDATE FILE_SUB SET SUB_ID = 1303 WHERE SUB_ID = 100;

INSERT INTO SCHEDULE (PHASE_NO,PHASE_DESC,DUE_DATE) VALUES (4,'DESIGN AND IMPLEMENTATION','2023-03-19'),(5,'SECURITY AND VALIDATION','2023-02-20'),(6,'MIDTERM REPORT','2023-03-01'),(7,'FINAL_DEMO','2023-03-10');

UPDATE FILE_SUB SET SUB_ID = 10031 WHERE SUB_ID = 1303;

ALTER TABLE FILE_SUB
ADD FOREIGN KEY (SUB_ID) REFERENCES PHASE_ALLOT(PHASE_ID);


CREATE TABLE TRANSACTIONS (
TRANSACTION_ID INTEGER auto_increment PRIMARY KEY,
SUB_ID INTEGER,
SUBMITTED_AT DATE,
SUB_STATUS VARCHAR(25),
FOREIGN KEY (SUB_ID) REFERENCES PHASE_ALLOT(PHASE_ID)
);

INSERT INTO TRANSACTIONS VALUES (10000,10031,'2023-02-13','LATE');
UPDATE TRANSACTIONS SET TRANSACTION_ID = 11000 WHERE TRANSACTION_ID = 10000;
SELECT S.PHASE_NO,S.PHASE_DESC,T.SUBMITTED_AT,T.SUB_STATUS FROM SCHEDULE AS S,TRANSACTIONS AS T,STUDENT AS ST,FILE_SUB AS F, PHASE_ALLOT AS PA, DELIVERABLE_PROJECT AS D WHERE T.SUB_ID = PA.PHASE_ID AND S.PHASE_NO = F.PHASE_NO AND PA.PROJECT_ID = D.PROJECT_ID AND F.USN = D.USN;

ALTER TABLE PHASE_ALLOT DROP COLUMN DUE_DATE;
ALTER TABLE PHASE_ALLOT DROP COLUMN LATE_SUBMISSION;

INSERT INTO PHASE_ALLOT (PHASE_ID,PROJECT_ID,PHASE_NO) VALUES (10032,1003,2),(10041,1004,1),(10051,1005,1),(10052,1005,2);
ALTER TABLE GUIDE RENAME COLUMN ID TO DIARY_ID;

USE DEPT_PROJECT;
UPDATE DELIVERABLE_PROJECT SET Project_Title = "Medical Chatbot" WHERE Project_ID = 1005;

CREATE TABLE PHASE_ALLOT (
phase_ID INTEGER PRIMARY KEY auto_increment,
Project_ID INTEGER,
phase_no INTEGER,
due_date DATE,
FOREIGN KEY (Project_ID) REFERENCES DELIVERABLE_PROJECT(Project_ID)
);

INSERT INTO PHASE_ALLOT VALUES (1203,1003,1,20222-09-03);
INSERT INTO PHASE_ALLOT VALUES (1204,1004,1,20222-10-04);
INSERT INTO PHASE_ALLOT VALUES (1205,1005,0,20222-10-23);
INSERT INTO PHASE_ALLOT VALUES (1206,1006,0,20222-09-03);

UPDATE PHASE_ALLOT SET Phase_ID = 1303 WHERE Phase_ID = 1203;
UPDATE PHASE_ALLOT SET Phase_ID = 1304 WHERE Phase_ID = 1204;

SELECT * FROM phase_allot;
SELECT * FROM TRANSACTIONS;
SELECT * FROM FILE_SUB;
SELECT * FROM deliverable_project;
SELECT * FROM TRANSACTIONS;
SELECT * FROM TRANSACTIONS;
SELECT * FROM DELIVERABLE_PROJECT;
SELECT * FROM FILE_SUB;
SELECT * FROM DELIVERABLE_PROJECT WHERE USN = '1RV20IS006';
SELECT * FROM FILE_SUB;
DESCRIBE FILE_SUB;

INSERT INTO FILE_SUB VALUES (10041,'1RV20IS006',1,'dept_project/static/DEPARTMENT_PROJECT_MANAGEMENT_SYSTEM/upload/economics_el_script.docx');
SELECT * FROM FILE_SUB;
SELECT * FROM DELIVERABLE_PROJECT;
SELECT * FROM PHASE_ALLOT;
DESCRIBE FILE_SUB;

SELECT * FROM FILE_SUB;

set foreign_key_checks = 0;
alter table FILE_SUB change column SUB_ID SUB_ID INT NOT NULL;
set foreign_key_checks = 1;
SELECT * FROM TRANSACTIONS;
SELECT * FROM DELIVERABLE_PROJECT;

SELECT * FROM FILE_SUB;