# Generated by Django 4.1.4 on 2023-01-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=25)),
                ('fname', models.CharField(max_length=25)),
                ('mname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'STUDENT',
            },
        ),
    ]
