# Generated by Django 4.1.4 on 2023-02-07 15:46

import dept_project.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverable_project',
            fields=[
                ('project_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Project_Title', models.CharField(max_length=50)),
                ('Project_Objective', models.CharField(max_length=150)),
                ('Project_Outcome', models.CharField(max_length=150)),
                ('project_Domain', models.CharField(max_length=100)),
                ('panel_ID', models.IntegerField(verbose_name=dept_project.models.panel_members)),
            ],
            options={
                'db_table': 'DELIVERABLE_PROJECT',
            },
        ),
        migrations.CreateModel(
            name='diary',
            fields=[
                ('diary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comments', models.CharField(max_length=100)),
                ('work_done', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DIARY',
            },
        ),
        migrations.CreateModel(
            name='guide',
            fields=[
                ('Guide_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('mname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('Phone_No', models.CharField(default=0, max_length=15)),
            ],
            options={
                'db_table': 'GUIDE',
            },
        ),
        migrations.CreateModel(
            name='panel_members',
            fields=[
                ('panel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usn', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'PANEL_MEMBERS',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
        migrations.RemoveField(
            model_name='student_input',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student_input',
            name='phone_no',
        ),
        migrations.AlterField(
            model_name='student_input',
            name='usn',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='phase_allot',
            fields=[
                ('phase_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('phase_no', models.IntegerField()),
                ('due_date', models.DateField()),
                ('late_submission', models.IntegerField()),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_project.deliverable_project')),
            ],
            options={
                'db_table': 'PHASE_ALLOT',
            },
        ),
        migrations.CreateModel(
            name='panel_allot',
            fields=[
                ('allot_num', models.AutoField(primary_key=True, serialize=False)),
                ('guide_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_project.guide')),
                ('panel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_project.panel_members')),
            ],
            options={
                'db_table': 'PANEL_ALLOT',
            },
        ),
        migrations.AddField(
            model_name='guide',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_project.users'),
        ),
        migrations.AddField(
            model_name='guide',
            name='id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept_project.diary'),
        ),
        migrations.AddField(
            model_name='guide',
            name='project_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept_project.deliverable_project'),
        ),
        migrations.AddField(
            model_name='guide',
            name='usn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept_project.student_input'),
        ),
        migrations.AddField(
            model_name='diary',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_project.student_input'),
        ),
        migrations.AddField(
            model_name='deliverable_project',
            name='usn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept_project.student_input'),
        ),
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=25)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dept_project.users')),
            ],
            options={
                'db_table': 'COORDINATOR',
            },
        ),
        migrations.AddField(
            model_name='student_input',
            name='Phone_no',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='student_input',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_project.users'),
        ),
    ]
