# Generated by Django 4.1.4 on 2023-02-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0002_deliverable_project_diary_guide_panel_members_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
    ]
