# Generated by Django 4.1.4 on 2023-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0007_file_submit_delete_student_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_submit',
            name='id',
        ),
        migrations.AddField(
            model_name='file_submit',
            name='sub_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='file_submit',
            name='usn',
            field=models.CharField(default='1RV20IS000', max_length=25),
        ),
        migrations.AlterModelTable(
            name='file_submit',
            table='FILE_SUB',
        ),
    ]
