# Generated by Django 4.1.4 on 2023-02-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0009_alter_file_submit_phase_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_submit',
            name='sub_id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
    ]
