# Generated by Django 2.2.24 on 2023-03-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0012_evaluateresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateresult',
            name='guide_no',
            field=models.CharField(default='1200', max_length=25),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
