# Generated by Django 2.2.24 on 2023-03-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0015_file_submit_eval'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_input',
            table=None,
        ),
    ]
