# Generated by Django 2.2.24 on 2023-03-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_project', '0016_auto_20230328_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_input',
            name='email',
            field=models.CharField(max_length=25),
        ),
    ]
